### ISSUE TITLE
Is it possible to specify shell script file at script part ?

### ISSUE THREAD

**Issue by jmawatari** [henry40408/concourse-ssh-resource#52]
Hello. I have a question.
Is it possible to specify shell script file at `script` part ?

If there is some method to specify, let me know how to do it.
Because I want to share script reusable in some pipeline.

```
jobs:
- name: echo
  plan:
  - put: staging-server
    params:
      interpreter: /bin/bash
      script: 
        path/to/somescript.sh  # <= this line
```
